language: node_js
node_js:
  - "node"
branches:
  only:
  - master-cli-v2
deploy:
  on:
    tags: true
  provider: npm
  email: "emin@emin.ch"
  api_key: "${NPM_TOKEN}"
  skip_cleanup: true
  tag: next
