# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :build_production do |options|
    gradle(
      task: "clean assembleRelease",
      properties: {
        "android.injected.signing.store.file" => File.join(Dir.pwd, "../app", "keystore"),
        "android.injected.signing.store.password" => options[:keystore_password],
        # Template TODO: Add alias.
        "android.injected.signing.key.alias" => "",
        "android.injected.signing.key.password" => options[:keystore_password]
      }
    )
  end
end
